<?php

namespace Database\Seeders;

use App\Models\Medicine;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MedicineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $medicines = [
            [
                'name' => 'CITRATO DE MAGNESIO',
                'composition' => 'MAGNESIO',
                'description' => 'SUPLEMENTO DE MAGNECIO, CALCIO Y POTASIO',
                'barcode' => '0000000096754',
                'buy_price' => 10,
                'sell_price' => 20,
                'igv' => 3.05,
                'profit' => 6.95,
                'stock' => 100,
                'salable' => true,
                'presentation' => 5,
            ],
            [
                'name' => 'SAL ROSADA PREMIUM',
                'composition' => 'SAL ROSADA ANDINA',
                'description' => 'SAL ROSADA DE LOS ANDES....',
                'barcode' => '0000000013686',
                'buy_price' => 15,
                'sell_price' => 28,
                'igv' => 4.27,
                'profit' => 8.73,
                'stock' => 20,
                'salable' => true,
                'presentation' => 8,
            ],
            [
                'name' => 'ACEITE DE COPAIBA',
                'composition' => 'ACEITE DE COPAIBA 30ML',
                'description' => 'Ha sido utilizado por miles de años como regenerador celular, cicatrizante, antiséptico, antiinflamatorio y analgésico.',
                'barcode' => '0000000023996',
                'buy_price' => 26,
                'sell_price' => 35,
                'igv' => 5.34,
                'profit' => 3.66,
                'stock' => 50,
                'salable' => true,
                'presentation' => 1,
            ],
            [
                'name' => 'SUPER SILUETA, BATIDOS',
                'composition' => 'PENCA DE TUNA, HABAS, LINAZA, AVENA',
                'description' => 'Super Silueta es el batido que ayuda a acelerar tu metabolismo y a purificar el aparato digestivo.',
                'barcode' => '0000000012074',
                'buy_price' => 90,
                'sell_price' => 109,
                'igv' => 16.63,
                'profit' => 2.37,
                'stock' => 25,
                'salable' => true,
                'presentation' => 4,
            ],
            [
                'name' => 'VITAMINA B12 - MASON NATURAL',
                'composition' => 'VITAMINA B12',
                'description' => 'LIBRE DE GLUTEN SIN AZÚCAR SIN LACTEOS SIN PRESERVANTES',
                'barcode' => '0000000033108',
                'buy_price' => 81,
                'sell_price' => 94,
                'igv' => 14.34,
                'profit' => 0,
                'stock' => 12,
                'salable' => true,
                'presentation' => 2,
            ],
            [
                'name' => 'ZINC INYECTABLE',
                'composition' => 'ZINC ----',
                'description' => 'ZINC ---- USO INTERNO',
                'barcode' => '0000000011074',
                'buy_price' => 25,
                'sell_price' => 25,
                'igv' => 0,
                'profit' => 0,
                'stock' => 50,
                'salable' => false,
                'presentation' => 9,
            ],
            [
                'name' => 'VITAMINA D INYECTABLE',
                'composition' => 'VITAMINA D ----',
                'description' => 'VITAMINA D INYECTABLE ---- USO INTERNO',
                'barcode' => '0000000077545',
                'buy_price' => 20,
                'sell_price' => 20,
                'igv' => 0,
                'profit' => 0,
                'stock' => 50,
                'salable' => false,
                'presentation' => 9,
            ],
            [
                'name' => 'VITAMINA B12 INYECTABLE',
                'composition' => 'VITAMINA B12 ----',
                'description' => 'VITAMINA B12 INYECTABLE ---- USO INTERNO',
                'barcode' => '0000000061852',
                'buy_price' => 20,
                'sell_price' => 20,
                'igv' => 0,
                'profit' => 0,
                'stock' => 24,
                'salable' => false,
                'presentation' => 9,
            ],
            [
                'name' => 'VITAMINA B50',
                'composition' => 'VITAMINA B50 ----',
                'description' => 'VITAMINA B50 INYECTABLE ---- USO INTERNO',
                'barcode' => '0000000065109',
                'buy_price' => 27,
                'sell_price' => 27,
                'igv' => 0,
                'profit' => 0,
                'stock' => 12,
                'salable' => false,
                'presentation' => 9,
            ],
            [
                'name' => 'CITRATO DE CALCIO',
                'composition' => 'CITRATO DE CALCIO ----',
                'description' => 'CITRATO DE CALCIO INYECTABLE ---- USO INTERNO',
                'barcode' => '0000000032105',
                'buy_price' => 17,
                'sell_price' => 17,
                'igv' => 0,
                'profit' => 0,
                'stock' => 5,
                'salable' => false,
                'presentation' => 9,
            ],
            [
                'name' => 'CREATINA MONOHIDRATADA',
                'composition' => 'CREATINA MONOHIDRATADA ----',
                'description' => 'CREATINA MONOHIDRATADA ---- USO INTERNO',
                'barcode' => '0000000054120',
                'buy_price' => 50,
                'sell_price' => 50,
                'igv' => 0,
                'profit' => 0,
                'stock' => 20,
                'salable' => false,
                'presentation' => 7,
            ],
            [
                'name' => 'ALCOHOL ISOPROPILICO 96% - 1LT',
                'composition' => 'ALCOHOL 96% ----',
                'description' => 'ALCOHOL DE 96 ---- USO INTERNO',
                'barcode' => '0000000011667',
                'buy_price' => 9,
                'sell_price' => 9,
                'igv' => 0,
                'profit' => 0,
                'stock' => 12,
                'salable' => false,
                'presentation' => 1,
            ],
            [
                'name' => 'TOCOSH CON UÑA DE GATO Y MUÑA',
                'composition' => 'TOCOSH, UÑA DE GATO Y MUÑA',
                'description' => 'Un superalimento con amplio poder antimicrobiano y desinflamante, que es parte de la medicina natural de los andes del Perú.',
                'barcode' => '0000000023880',
                'buy_price' => 70,
                'sell_price' => 88,
                'igv' => 13.42,
                'profit' => 4.58,
                'stock' => 8,
                'salable' => true,
                'presentation' => 13,
            ],
            [
                'name' => 'MIEL DE ABEJAS SANTA NATURA',
                'composition' => 'MIEL DE ABEJAS.',
                'description' => 'La Miel de Abejas Santa Natura es producida por las abejas a partir de la combinación del néctar de flores extraído de la Amazonía virgen.',
                'barcode' => '0000000041087',
                'buy_price' => 30,
                'sell_price' => 40,
                'igv' => 6.1,
                'profit' => 3.9,
                'stock' => 50,
                'salable' => true,
                'presentation' => 10,
            ],
            [
                'name' => 'SHAMPOO DE QUINA',
                'composition' => 'QUINA, DETERGENTE, GLICERINA, PRESERVANTE',
                'description' => 'Cuida tu cabello y previene su caída de manera natural con nuestro Shampoo de Quina Santa Natura.',
                'barcode' => '0000000061209',
                'buy_price' => 76,
                'sell_price' => 99,
                'igv' => 15.1,
                'profit' => 7.9,
                'stock' => 6,
                'salable' => true,
                'presentation' => 11,
            ],
            [
                'name' => 'MIEL DE ABEJAS CON PROPOLEOS',
                'composition' => 'MIEL DE ABEJA + PROPOLEOS + CONSERVANTES',
                'description' => '¡Ayuda a elevar tus defensas con la dulce protección de la miel enriquecida con propóleos!',
                'barcode' => '0000000070120',
                'buy_price' => 45,
                'sell_price' => 60,
                'igv' => 9.15,
                'profit' => 5.85,
                'stock' => 30,
                'salable' => true,
                'presentation' => 12,
            ],
            [
                'name' => 'RESINA DE PLATANO CON MIEL DE ABEJA',
                'composition' => 'PLATANO + MIEL DE ABEJA + PRESERVANTES',
                'description' => 'Las medicinas tradicionales utilizan la savia o resina del plátano para defender al sistema...',
                'barcode' => '0000000017139',
                'buy_price' => 45,
                'sell_price' => 60,
                'igv' => 9.15,
                'profit' => 5.85,
                'stock' => 12,
                'salable' => true,
                'presentation' => 12,
            ],
            [
                'name' => 'MORINGA CON PROTEINAS VEGETALES',
                'composition' => 'MORINGAAA....',
                'description' => '¡Ayuda a potenciar tu función cerebral y protégete de la degeneración neuronal!',
                'barcode' => '0000000006271',
                'buy_price' => 70,
                'sell_price' => 88,
                'igv' => 13.42,
                'profit' => 4.58,
                'stock' => 25,
                'salable' => true,
                'presentation' => 13,
            ],
            [
                'name' => 'HARINA GELATINIZADA DE MACA',
                'composition' => 'MEZCLA DE MACAS DE COLORES: AMARILLA, ROJA, NEGRA.',
                'description' => '¡Ayuda a aumentar tu fuerza y energía con la Harina Gelatinizada de Maca!',
                'barcode' => '0000000003379',
                'buy_price' => 48,
                'sell_price' => 60,
                'igv' => 9.15,
                'profit' => 2.85,
                'stock' => 16,
                'salable' => true,
                'presentation' => 5,
            ],
        ];

        foreach ($medicines as $m) {
            $medicine = Medicine::create([
                'name' => $m['name'],
                'composition' => $m['composition'],
                'description' => $m['description'],
                'barcode' => $m['barcode'],
                'buy_price' => $m['buy_price'],
                'sell_price' => $m['sell_price'],
                'igv' => $m['igv'],
                'profit' => $m['profit'],
                'stock' => $m['stock'],
                'salable' => $m['salable'],
                'presentation' => $m['presentation'],
            ]);
            $randomSupplier = rand(1, 40);
            $medicine->suppliers()->sync([$randomSupplier]);
        }
    }
}
